// core/mesh.js — the numbers the whole report is built from. The bounding box drives the fit
// check and the declared-vs-measured check, the normals drive the overhang bands, the volume
// drives the filament figure.
//
// Every measurement here has a closed-form answer, so every assertion below is against
// arithmetic rather than against a previous run of this code. Two solids do the work: the
// 2 mm cube, whose every answer is a small whole number, and a regular tetrahedron of edge 10,
// which exists precisely because the cube is too forgiving — 8 mm^3 is what several wrong
// volume formulas also produce, and the cube's axis-aligned faces hide sign errors that a
// solid with no axis-aligned face does not.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { parseStl } from '../core/stl.js';
import {
  boundingBox,
  signedVolume,
  surfaceArea,
  triangleAreas,
  triangleNormals,
  centroid,
  filamentFromVolume,
} from '../core/mesh.js';

const FIXTURES = fileURLToPath(new URL('./fixtures/', import.meta.url));

/** @param {string} name @returns {Float32Array} the positions of a committed fixture */
const positionsOf = (name) => parseStl(new Uint8Array(readFileSync(`${FIXTURES}${name}`))).positions;

const CUBE = positionsOf('cube-binary.stl');
const TETRAHEDRON = positionsOf('tetrahedron.stl');
const DEGENERATE = positionsOf('degenerate.stl');
const EMPTY = positionsOf('empty.stl');
const OPEN_BOX = positionsOf('open-box.stl');

// The closed forms, spelled out rather than pasted from a run. Edge 10: V = a^3 / (6 sqrt 2),
// A = sqrt(3) a^2.
const TET_VOLUME = 1000 / (6 * Math.SQRT2); // 117.85113019775791
const TET_AREA = Math.sqrt(3) * 100; //        173.20508075688772

/** @param {number[] | Float32Array} values @param {number[]} expected @param {number} epsilon */
function assertClose(values, expected, epsilon, what = 'value') {
  assert.equal(values.length, expected.length, `${what}: wrong length`);
  for (let at = 0; at < expected.length; at++) {
    assert.ok(
      Math.abs(values[at] - expected[at]) <= epsilon,
      `${what}[${at}]: ${values[at]} is not within ${epsilon} of ${expected[at]}`,
    );
  }
}

/**
 * Apply a per-coordinate map, through float32 so the result is the mesh a file would hold.
 *
 * @param {Float32Array} positions
 * @param {(value: number, axis: number) => number} fn
 * @returns {Float32Array}
 */
function mapCoordinates(positions, fn) {
  const out = new Float32Array(positions.length);
  for (let at = 0; at < positions.length; at++) out[at] = fn(positions[at], at % 3);
  return out;
}

/**
 * The same triangles with vertices 1 and 2 swapped, which reverses every winding and so turns
 * the solid inside out without moving a single point.
 *
 * @param {Float32Array} positions
 * @returns {Float32Array}
 */
function reverseWinding(positions) {
  const out = Float32Array.from(positions);
  for (let at = 0; at < positions.length; at += 9) {
    for (let k = 0; k < 3; k++) {
      out[at + 3 + k] = positions[at + 6 + k];
      out[at + 6 + k] = positions[at + 3 + k];
    }
  }
  return out;
}

/** Every number this module can produce for a mesh, flattened. @param {Float32Array} p */
function everyMeasurement(p) {
  const box = boundingBox(p);
  return [
    ...box.min,
    ...box.max,
    ...box.size,
    signedVolume(p),
    surfaceArea(p),
    ...triangleAreas(p),
    ...triangleNormals(p),
    ...centroid(p),
  ];
}

// --- the cube: every answer a small whole number ------------------------------------------

test('2 mm cube: bounding box is [0,0,0]..[2,2,2]', () => {
  const box = boundingBox(CUBE);
  assert.equal(box.isEmpty, false);
  assert.deepEqual(box.min, [0, 0, 0]);
  assert.deepEqual(box.max, [2, 2, 2]);
  assert.deepEqual(box.size, [2, 2, 2]);
});

test('2 mm cube: volume 8, area 24, centroid [1,1,1]', () => {
  assert.ok(Math.abs(signedVolume(CUBE) - 8) < 1e-4, `volume ${signedVolume(CUBE)}`);
  assert.ok(Math.abs(surfaceArea(CUBE) - 24) < 1e-4, `area ${surfaceArea(CUBE)}`);
  assertClose(centroid(CUBE), [1, 1, 1], 1e-4, 'centroid');
});

// --- the tetrahedron: the fixture that catches what the cube cannot ------------------------

test('regular tetrahedron edge 10: volume 117.8511..., area 173.2050...', () => {
  assert.ok(
    Math.abs(signedVolume(TETRAHEDRON) - TET_VOLUME) < 1e-3,
    `volume ${signedVolume(TETRAHEDRON)}, expected ${TET_VOLUME}`,
  );
  assert.ok(
    Math.abs(surfaceArea(TETRAHEDRON) - TET_AREA) < 1e-3,
    `area ${surfaceArea(TETRAHEDRON)}, expected ${TET_AREA}`,
  );
});

test('regular tetrahedron: the fixture really has edge 10 and is centred on the origin', () => {
  // The fixture is generated by tools/make-fixtures.mjs, which shares no code with core/. If
  // its arithmetic were wrong the volume test above would be checking the wrong solid, so the
  // solid itself is checked here: all six edges 10, centroid at the origin, four faces.
  assert.equal(TETRAHEDRON.length / 9, 4);
  const at = (corner) => [TETRAHEDRON[corner * 3], TETRAHEDRON[corner * 3 + 1], TETRAHEDRON[corner * 3 + 2]];
  const seen = new Map();
  for (let corner = 0; corner < TETRAHEDRON.length / 3; corner++) {
    seen.set(at(corner).join(','), at(corner));
  }
  const vertices = [...seen.values()];
  assert.equal(vertices.length, 4, 'a tetrahedron has four distinct vertices');
  for (let i = 0; i < 4; i++) {
    for (let j = i + 1; j < 4; j++) {
      const edge = Math.hypot(...vertices[i].map((v, k) => v - vertices[j][k]));
      assert.ok(Math.abs(edge - 10) < 1e-5, `edge ${i}-${j} is ${edge}, not 10`);
    }
  }
  assertClose(centroid(TETRAHEDRON), [0, 0, 0], 1e-5, 'centroid');
});

test('regular tetrahedron: each of the four faces has area sqrt(3)/4 * 100', () => {
  const areas = triangleAreas(TETRAHEDRON);
  assert.equal(areas.length, 4);
  const faceArea = (Math.sqrt(3) / 4) * 100;
  for (const area of areas) {
    assert.ok(Math.abs(area - faceArea) < 1e-3, `face area ${area}, expected ${faceArea}`);
  }
});

// --- invariance: what moving and scaling a solid must and must not change -----------------

test('translating the cube by [100,-50,7] leaves volume and area alone and moves the centroid', () => {
  const offsets = [100, -50, 7];
  const moved = mapCoordinates(CUBE, (value, axis) => value + offsets[axis]);
  // The divergence-theorem sum is taken about the origin, so a translated solid's terms are
  // large numbers that have to cancel back down to 8. That is the algebra being checked here
  // — origin-independence — and not the arithmetic precision: this cube's coordinates are
  // small exact integers, so the sum is exact whatever it is accumulated in. The precision
  // limit is measured separately, in the large-mesh test below.
  assert.ok(Math.abs(signedVolume(moved) - 8) < 1e-4, `volume ${signedVolume(moved)}`);
  assert.ok(Math.abs(surfaceArea(moved) - 24) < 1e-4, `area ${surfaceArea(moved)}`);
  assertClose(centroid(moved), [101, -49, 8], 1e-4, 'centroid');
  assert.deepEqual(boundingBox(moved).size, [2, 2, 2]);
  assert.deepEqual(boundingBox(moved).min, [100, -50, 7]);
});

test('scaling the cube by 10 multiplies volume by 1000 and area by 100', () => {
  const bigger = mapCoordinates(CUBE, (value) => value * 10);
  assert.ok(Math.abs(signedVolume(bigger) - 8000) < 1e-2, `volume ${signedVolume(bigger)}`);
  assert.ok(Math.abs(surfaceArea(bigger) - 2400) < 1e-2, `area ${surfaceArea(bigger)}`);
  assertClose(centroid(bigger), [10, 10, 10], 1e-3, 'centroid');
  assert.deepEqual(boundingBox(bigger).size, [20, 20, 20]);
});

test('volume of a large mesh far from the origin is good to about three figures', () => {
  // 20 000 copies of the tetrahedron, laid out along X so the sum runs over coordinates up to
  // 400 000 mm — far past anything this printer will see, and deliberately so: it is where the
  // divergence sum's cancellation is worst, and it pins how many digits of a measured volume
  // are real.
  //
  // The measured relative error is ~6.7e-4. **Almost all of it is the float32 coordinates
  // themselves, not the accumulation** — an STL stores float32 and there is no getting that
  // back, which is why accumulating the sum in float64 (as this module does) is worth doing
  // and yet cannot be demonstrated by comparing against the closed form. See FINDINGS.md.
  //
  // This is a regression guard with a loose bound, not a tight claim: it exists so that a
  // later change which made the arithmetic markedly worse would be noticed.
  const copies = 20000;
  const many = new Float32Array(TETRAHEDRON.length * copies);
  for (let copy = 0; copy < copies; copy++) {
    for (let at = 0; at < TETRAHEDRON.length; at++) {
      many[copy * TETRAHEDRON.length + at] = TETRAHEDRON[at] + (at % 3 === 0 ? copy * 20 : 0);
    }
  }
  const expected = TET_VOLUME * copies;
  const relativeError = Math.abs(signedVolume(many) - expected) / expected;
  assert.ok(relativeError < 2e-3, `relative error ${relativeError.toExponential(2)}`);
});

test('a cube wound inside-out has volume -8 and the same surface area', () => {
  const inverted = reverseWinding(CUBE);
  // The sign is the whole point: T04 reports an overall-negative volume as "inside-out", and
  // an abs() anywhere in signedVolume would delete the clearest symptom a broken mesh has.
  assert.ok(Math.abs(signedVolume(inverted) + 8) < 1e-4, `volume ${signedVolume(inverted)}`);
  assert.ok(signedVolume(inverted) < 0, 'reversed winding must give a negative volume');
  assert.ok(Math.abs(surfaceArea(inverted) - 24) < 1e-4, 'area is unsigned and must not change');
  assert.deepEqual(boundingBox(inverted).size, [2, 2, 2], 'no point moved');
});

test('the tetrahedron wound inside-out gives the same volume negated', () => {
  const inverted = reverseWinding(TETRAHEDRON);
  assert.ok(
    Math.abs(signedVolume(inverted) + TET_VOLUME) < 1e-3,
    `volume ${signedVolume(inverted)}`,
  );
});

// --- normals ------------------------------------------------------------------------------

test('triangleNormals on the cube gives the six axis directions, each exactly twice', () => {
  const normals = triangleNormals(CUBE);
  assert.equal(normals.length, 12 * 3);
  const tally = new Map();
  for (let tri = 0; tri < 12; tri++) {
    const key = [...normals.slice(tri * 3, tri * 3 + 3)].join(',');
    tally.set(key, (tally.get(key) ?? 0) + 1);
  }
  const expected = ['1,0,0', '-1,0,0', '0,1,0', '0,-1,0', '0,0,1', '0,0,-1'];
  assert.deepEqual([...tally.keys()].sort(), [...expected].sort());
  for (const direction of expected) {
    assert.equal(tally.get(direction), 2, `${direction} should appear twice`);
  }
});

test('triangleNormals come from the winding, not from the file — reversing flips every one', () => {
  const forward = triangleNormals(CUBE);
  const backward = triangleNormals(reverseWinding(CUBE));
  for (let at = 0; at < forward.length; at++) {
    assert.equal(backward[at], -forward[at] === 0 ? 0 : -forward[at]);
  }
});

test('triangleNormals on the tetrahedron are unit vectors pointing away from the centre', () => {
  const normals = triangleNormals(TETRAHEDRON);
  for (let tri = 0; tri < 4; tri++) {
    const n = [...normals.slice(tri * 3, tri * 3 + 3)];
    assert.ok(Math.abs(Math.hypot(...n) - 1) < 1e-6, `normal ${tri} is not a unit vector: ${n}`);
    // The solid is centred on the origin, so an outward normal has a positive dot product
    // with the vector from the origin to the face's own centre.
    const at = tri * 9;
    const face = [0, 1, 2].map(
      (axis) => (TETRAHEDRON[at + axis] + TETRAHEDRON[at + 3 + axis] + TETRAHEDRON[at + 6 + axis]) / 3,
    );
    const dot = n[0] * face[0] + n[1] * face[1] + n[2] * face[2];
    assert.ok(dot > 0, `normal ${tri} points inward: n=${n}, face centre=${face}`);
  }
});

test('degenerate.stl: the zero-area triangle gets [0,0,0], not NaN', () => {
  const normals = triangleNormals(DEGENERATE);
  assert.deepEqual([...normals.slice(0, 3)], [0, 0, 1], 'the honest triangle is unaffected');
  assert.deepEqual([...normals.slice(3, 6)], [0, 0, 0], 'the collinear one has no normal');
  for (const value of normals) assert.ok(Number.isFinite(value), `${value} is not finite`);
});

test('degenerate.stl: no measurement anywhere is NaN or Infinity', () => {
  for (const value of everyMeasurement(DEGENERATE)) {
    assert.ok(Number.isFinite(value), `${value} is not finite`);
  }
  assert.deepEqual([...triangleAreas(DEGENERATE)], [0.5, 0]);
});

// --- areas --------------------------------------------------------------------------------

test('triangleAreas sums to surfaceArea, on both solids and on the open box', () => {
  for (const [name, mesh] of [['cube', CUBE], ['tetrahedron', TETRAHEDRON], ['open box', OPEN_BOX]]) {
    const summed = [...triangleAreas(mesh)].reduce((a, b) => a + b, 0);
    const total = surfaceArea(mesh);
    // Not exact: triangleAreas rounds each face to float32 on the way out, surfaceArea keeps
    // the running total in float64. A relative tolerance is the honest comparison.
    assert.ok(
      Math.abs(summed - total) <= Math.max(total, 1) * 1e-6,
      `${name}: parts sum to ${summed}, whole is ${total}`,
    );
  }
});

test('triangleAreas and triangleNormals return Float32Arrays, one entry per triangle', () => {
  // The type is part of the interface: T05 walks these per triangle over a mesh that can run
  // to hundreds of thousands, and a plain array or a Float64Array would double the memory the
  // viewer and the report share.
  for (const [name, mesh, count] of [['cube', CUBE, 12], ['tetrahedron', TETRAHEDRON, 4], ['empty', EMPTY, 0]]) {
    const areas = triangleAreas(mesh);
    const normals = triangleNormals(mesh);
    assert.ok(areas instanceof Float32Array, `${name}: areas are ${areas.constructor.name}`);
    assert.ok(normals instanceof Float32Array, `${name}: normals are ${normals.constructor.name}`);
    assert.equal(areas.length, count, `${name}: one area per triangle`);
    assert.equal(normals.length, count * 3, `${name}: three normal components per triangle`);
  }
});

// --- the empty mesh -------------------------------------------------------------------------

test('empty mesh: bounding box reports isEmpty and zeros, never Infinity', () => {
  const box = boundingBox(EMPTY);
  assert.equal(box.isEmpty, true);
  assert.deepEqual(box.min, [0, 0, 0]);
  assert.deepEqual(box.max, [0, 0, 0]);
  assert.deepEqual(box.size, [0, 0, 0]);
  // The naive fold seeds with +/-Infinity and returns it untouched. DESIGN.md §2.10: an empty
  // mesh is an absence, and the flag is what lets T07 say so instead of printing a size.
  for (const value of [...box.min, ...box.max, ...box.size]) {
    assert.ok(Number.isFinite(value), `${value} is not finite`);
  }
});

test('empty mesh: volume 0, area 0, centroid at the origin, nothing NaN', () => {
  assert.equal(signedVolume(EMPTY), 0);
  assert.equal(surfaceArea(EMPTY), 0);
  assert.deepEqual(centroid(EMPTY), [0, 0, 0]);
  assert.equal(triangleNormals(EMPTY).length, 0);
  for (const value of everyMeasurement(EMPTY)) {
    assert.ok(Number.isFinite(value), `${value} is not finite`);
  }
});

// --- the open box: a mesh that is not a solid ----------------------------------------------

test('open-box.stl: every measurement is finite and the centroid stays inside the box', () => {
  const box = boundingBox(OPEN_BOX);
  assert.deepEqual(box.size, [2, 2, 2]);
  for (const value of everyMeasurement(OPEN_BOX)) {
    assert.ok(Number.isFinite(value), `${value} is not finite`);
  }
  // A centre of mass lies within the convex hull of the points and so within the bounding box.
  // That holds however open the mesh is, and it is the invariant centroid()'s fallback chain
  // is built on, so it is asserted on the one fixture that is not a closed solid.
  const centre = centroid(OPEN_BOX);
  for (let axis = 0; axis < 3; axis++) {
    assert.ok(
      centre[axis] >= box.min[axis] - 1e-5 && centre[axis] <= box.max[axis] + 1e-5,
      `centroid ${centre} escapes the bounding box on axis ${axis}`,
    );
  }
});

test('a zero-thickness wall has zero volume and still reports a usable centroid', () => {
  // A 4 x 4 square in the z = 3 plane, present twice with opposite windings — the mesh a
  // recipe produces when a wall is given no thickness. It encloses nothing, so the signed
  // volume cancels to zero and the volume-weighted formula is 0/0; the area-weighted fallback
  // is the square's own centre.
  //
  // Note that a *one-sided* plate is not zero-volume: about the origin each triangle spans a
  // cone, and the same square facing one way alone measures 16 mm^3. It is the cancellation
  // that makes this zero, which is exactly the case the fallback exists for.
  const oneSide = [
    0, 0, 3, 4, 0, 3, 4, 4, 3,
    0, 0, 3, 4, 4, 3, 0, 4, 3,
  ];
  const wall = Float32Array.from([...oneSide, ...reverseWinding(Float32Array.from(oneSide))]);
  assert.ok(Math.abs(signedVolume(wall)) < 1e-9, `volume ${signedVolume(wall)}`);
  assert.ok(Math.abs(surfaceArea(wall) - 32) < 1e-5, `area ${surfaceArea(wall)}`);
  assertClose(centroid(wall), [2, 2, 3], 1e-5, 'centroid');
});

test('the zero-volume fallback weights by area, not by counting triangles', () => {
  // A 4 x 4 square and one 0.1 mm sliver 100 mm away, both double-sided so the volume cancels
  // to zero exactly. The square is 3200 times the area of the sliver, so the centre of mass of
  // this surface sits essentially on the square.
  //
  // Counting triangles instead — averaging the vertices, which is the last rung of the chain —
  // gives the sliver a third of the vote, because it is two of the six triangles, and puts the
  // answer at x = 34.7 mm: out in empty space, nowhere near either piece of the mesh. That is
  // the mistake this test rules out.
  const reversed = (t) => [t[0], t[1], t[2], t[6], t[7], t[8], t[3], t[4], t[5]];
  const half1 = [0, 0, 3, 4, 0, 3, 4, 4, 3];
  const half2 = [0, 0, 3, 4, 4, 3, 0, 4, 3];
  const sliver = [100, 0, 3, 100.1, 0, 3, 100, 0.1, 3];
  const mesh = Float32Array.from([
    ...half1, ...half2, ...reversed(half1), ...reversed(half2), ...reversed(sliver), ...sliver,
  ]);

  assert.equal(signedVolume(mesh), 0, 'the two windings must cancel exactly');

  // The closed form, from the two pieces rather than from a previous run.
  const squareArea = 2 * 16;
  const sliverArea = 2 * 0.5 * 0.1 * 0.1;
  const sliverCentre = [100 + 0.1 / 3, 0.1 / 3, 3];
  const total = squareArea + sliverArea;
  const expected = [0, 1, 2].map(
    (axis) => (squareArea * [2, 2, 3][axis] + sliverArea * sliverCentre[axis]) / total,
  );
  assertClose(centroid(mesh), expected, 1e-3, 'area-weighted centroid');

  const vertexAverage = [...mesh].filter((_, at) => at % 3 === 0).reduce((a, b) => a + b, 0) / 18;
  assert.ok(vertexAverage > 30, `the vertex average should be far off: ${vertexAverage}`);
  assert.ok(
    Math.abs(centroid(mesh)[0] - vertexAverage) > 30,
    'the centroid must not be the vertex average',
  );
});

test('a mesh of nothing but zero-area triangles falls back to the average of its vertices', () => {
  // Volume zero and area zero together, which is the last rung of the fallback chain. The
  // three collinear points average to (2, 0, 0).
  const collinear = Float32Array.from([0, 0, 0, 1, 0, 0, 5, 0, 0]);
  assert.equal(surfaceArea(collinear), 0);
  assertClose(centroid(collinear), [2, 0, 0], 1e-6, 'centroid');
});

test('a centroid that escapes its own bounding box is discarded, not reported', () => {
  // The case the fallback's bounding-box check exists for, and it is not hypothetical noise:
  // two triangles 200 mm apart whose volume contributions very nearly cancel while their
  // moments add. The volume-weighted formula then divides a large number by a tiny one.
  //
  // Measured: without the check this mesh reports a centre of mass at x = -750 000 037 mm,
  // for a mesh whose every point lies between -100 and +100. A centre of mass always lies
  // within the convex hull of the points and so within the bounding box, so a result outside
  // it is arithmetic, not geometry, and the area-weighted answer (x ~ 0, the midpoint of two
  // equal triangles) is taken instead.
  const nearCancelling = Float64Array.from([
    100, 0, 0, 100, 1, 0, 100, 0, 1,
    -100, 0, 0, -100, 1.0000001, 0, -100, 0, 1.0000001,
  ]);
  const box = boundingBox(nearCancelling);
  assert.deepEqual(box.min, [-100, 0, 0]);
  assert.deepEqual(box.max, [100, 1.0000001, 1.0000001]);
  const centre = centroid(nearCancelling);
  for (let axis = 0; axis < 3; axis++) {
    assert.ok(
      centre[axis] >= box.min[axis] - 1e-5 && centre[axis] <= box.max[axis] + 1e-5,
      `centroid ${centre} escapes the bounding box on axis ${axis}`,
    );
  }
  assertClose(centre, [0, 1 / 3, 1 / 3], 1e-4, 'area-weighted centroid');
});

// --- filament -------------------------------------------------------------------------------

test('filamentFromVolume: 2405.28 mm^3 of PLA is about 1 m of 1.75 mm filament', () => {
  const filament = filamentFromVolume(2405.28, 1.24);
  assert.equal(filament.volumeMm3, 2405.28);
  assert.ok(Math.abs(filament.lengthMm - 1000) < 0.01, `length ${filament.lengthMm}`);
  assert.ok(Math.abs(filament.grams - 2.98) < 0.005, `grams ${filament.grams}`);
});

test('filamentFromVolume: the cross-section is really PI * (1.75/2)^2', () => {
  // One metre of filament, by arithmetic rather than by the constant in the module.
  const oneMetre = Math.PI * (1.75 / 2) ** 2 * 1000;
  assert.ok(Math.abs(filamentFromVolume(oneMetre, 1.24).lengthMm - 1000) < 1e-6);
});

test('filamentFromVolume(0, ...) is zeros, not NaN', () => {
  const filament = filamentFromVolume(0, 1.24);
  assert.deepEqual(filament, { volumeMm3: 0, lengthMm: 0, grams: 0 });
});

test('filamentFromVolume passes a negative volume through rather than hiding it', () => {
  // An inside-out mesh gives a negative volume. Making it positive here would present a
  // confident figure for a mesh T04 is about to report as broken.
  const filament = filamentFromVolume(-2405.28, 1.24);
  assert.ok(filament.lengthMm < 0, `length ${filament.lengthMm}`);
  assert.ok(filament.grams < 0, `grams ${filament.grams}`);
});

test('filamentFromVolume rejects a non-numeric or non-finite argument', () => {
  assert.throws(() => filamentFromVolume(Number.NaN, 1.24), TypeError);
  assert.throws(() => filamentFromVolume(Infinity, 1.24), TypeError);
  assert.throws(() => filamentFromVolume('8', 1.24), TypeError);
  assert.throws(() => filamentFromVolume(8, Number.NaN), TypeError);
  assert.throws(() => filamentFromVolume(8, null), TypeError);
});

// --- what the callers may hand in -----------------------------------------------------------

test('positions may be a Float64Array or a plain array, not only a Float32Array', () => {
  const asFloat64 = Float64Array.from(CUBE);
  const asArray = [...CUBE];
  for (const mesh of [asFloat64, asArray]) {
    assert.ok(Math.abs(signedVolume(mesh) - 8) < 1e-4);
    assert.ok(Math.abs(surfaceArea(mesh) - 24) < 1e-4);
    assert.deepEqual(boundingBox(mesh).size, [2, 2, 2]);
    assertClose(centroid(mesh), [1, 1, 1], 1e-4, 'centroid');
  }
});

test('a ragged positions array is a caller bug and throws RangeError', () => {
  const ragged = Float32Array.from([0, 0, 0, 1, 0, 0, 0, 1]); // eight values, not nine
  for (const fn of [boundingBox, signedVolume, surfaceArea, triangleAreas, triangleNormals, centroid]) {
    assert.throws(() => fn(ragged), RangeError, `${fn.name} accepted a ragged array`);
  }
});

test('a non-array positions argument throws TypeError, not a mesh complaint', () => {
  for (const fn of [boundingBox, signedVolume, surfaceArea, triangleAreas, triangleNormals, centroid]) {
    assert.throws(() => fn('solid'), TypeError, `${fn.name} accepted a string`);
    assert.throws(() => fn(undefined), TypeError, `${fn.name} accepted undefined`);
    // A Uint8Array is bytes, not coordinates — handing the file to the measurer by mistake.
    assert.throws(() => fn(new Uint8Array(9)), TypeError, `${fn.name} accepted bytes`);
  }
});
